### **WORKING ON COMBING MULTIPLE LEAD FILES**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#importing libraries
import pandas as pd
import numpy as np
import os
from natsort import natsorted

#creating list to store file_names
NORMAL_=[]
MI_=[]
PMI_=[]
HB_=[]

normal = "/content/drive/MyDrive/Cardiovascular-Detection-using-ECG-images-main/ECG_IMAGES_DATASET/Normal Person ECG Images (284x12=3408)"
abnormal = "/content/drive/MyDrive/Cardiovascular-Detection-using-ECG-images-main/ECG_IMAGES_DATASET/ECG Images of Patient that have abnormal heartbeat (233x12=2796)"
MI = "/content/drive/MyDrive/Cardiovascular-Detection-using-ECG-images-main/ECG_IMAGES_DATASET/ECG Images of Myocardial Infarction Patients (240x12=2880)"
MI_history = "/content/drive/MyDrive/Cardiovascular-Detection-using-ECG-images-main/ECG_IMAGES_DATASET/ECG Images of Patient that have History of MI (172x12=2064)"

Types_ECG = {'normal':normal,'Abnormal_hear_beat':abnormal,'MI':MI,'History_MI':MI_history}

for types,folder in Types_ECG.items():
  for files in os.listdir(folder):
    if types=='normal':
      NORMAL_.append(files)
    elif types=='Abnormal_hear_beat':
      HB_.append(files)
    elif types=='MI':
      MI_.append(files)
    elif types=='History_MI':
      PMI_.append(files)

In [4]:
NORMAL_.sort()
NORMAL_

['Normal(1)',
 'Normal(1).jpg',
 'Normal(10)',
 'Normal(10).jpg',
 'Normal(100)',
 'Normal(100).jpg',
 'Normal(101)',
 'Normal(101).jpg',
 'Normal(102)',
 'Normal(102).jpg',
 'Normal(103)',
 'Normal(103).jpg',
 'Normal(104)',
 'Normal(104).jpg',
 'Normal(105)',
 'Normal(105).jpg',
 'Normal(106)',
 'Normal(106).jpg',
 'Normal(107)',
 'Normal(107).jpg',
 'Normal(108)',
 'Normal(108).jpg',
 'Normal(109)',
 'Normal(109).jpg',
 'Normal(11)',
 'Normal(11).jpg',
 'Normal(110)',
 'Normal(110).jpg',
 'Normal(111)',
 'Normal(111).jpg',
 'Normal(112)',
 'Normal(112).jpg',
 'Normal(113)',
 'Normal(113).jpg',
 'Normal(114)',
 'Normal(114).jpg',
 'Normal(115)',
 'Normal(115).jpg',
 'Normal(116)',
 'Normal(116).jpg',
 'Normal(117)',
 'Normal(117).jpg',
 'Normal(118)',
 'Normal(118).jpg',
 'Normal(119)',
 'Normal(119).jpg',
 'Normal(12)',
 'Normal(12).jpg',
 'Normal(120)',
 'Normal(120).jpg',
 'Normal(121)',
 'Normal(121).jpg',
 'Normal(122)',
 'Normal(122).jpg',
 'Normal(123)',
 'Normal(123).jpg',
 'Normal(124)',
 'Normal(124).jpg',
 'Normal(125)',
 'Normal(125).jpg',
 'Normal(126)',
 'Normal(126).jpg',
 'Normal(127)',
 'Normal(127).jpg',
 'Normal(128)',
 'Normal(128).jpg',
 'Normal(129)',
 'Normal(129).jpg',
 'Normal(13)',
 'Normal(13).jpg',
 'Normal(130)',
 'Normal(130).jpg',
 'Normal(131)',
 'Normal(131).jpg',
 'Normal(132)',
 'Normal(132).jpg',
 'Normal(133)',
 'Normal(133).jpg',
 'Normal(134)',
 'Normal(134).jpg',
 'Normal(135)',
 'Normal(135).jpg',
 'Normal(136)',
 'Normal(136).jpg',
 'Normal(137)',
 'Normal(137).jpg',
 'Normal(138)',
 'Normal(138).jpg',
 'Normal(139)',
 'Normal(139).jpg',
 'Normal(14)',
 'Normal(14).jpg',
 'Normal(140)',
 'Normal(140).jpg',
 'Normal(141)',
 'Normal(141).jpg',
 'Normal(142)',
 'Normal(142).jpg',
 'Normal(143)',
 'Normal(143).jpg',
 'Normal(144)',
 'Normal(144).jpg',
 'Normal(145)',
 'Normal(145).jpg',
 'Normal(146)',
 'Normal(146).jpg',
 'Normal(147)',
 'Normal(147).jpg',
 'Normal(148)',
 'Normal(148).jpg',
 'Normal(149)',
 'Normal(149).jpg',
 'Normal(15)',
 'Normal(15).jpg',
 'Normal(150)',
 'Normal(150).jpg',
 'Normal(151)',
 'Normal(151).jpg',
 'Normal(152)',
 'Normal(152).jpg',
 'Normal(153)',
 'Normal(153).jpg',
 'Normal(154)',
 'Normal(154).jpg',
 'Normal(155)',
 'Normal(155).jpg',
 'Normal(156)',
 'Normal(156).jpg',
 'Normal(157)',
 'Normal(157).jpg',
 'Normal(158)',
 'Normal(158).jpg',
 'Normal(159)',
 'Normal(159).jpg',
 'Normal(16)',
 'Normal(16).jpg',
 'Normal(160)',
 'Normal(160).jpg',
 'Normal(161)',
 'Normal(161).jpg',
 'Normal(162)',
 'Normal(162).jpg',
 'Normal(163)',
 'Normal(163).jpg',
 'Normal(164)',
 'Normal(164).jpg',
 'Normal(165)',
 'Normal(165).jpg',
 'Normal(166)',
 'Normal(166).jpg',
 'Normal(167)',
 'Normal(167).jpg',
 'Normal(168)',
 'Normal(168).jpg',
 'Normal(169)',
 'Normal(169).jpg',
 'Normal(17)',
 'Normal(17).jpg',
 'Normal(170)',
 'Normal(170).jpg',
 'Normal(171)',
 'Normal(171).jpg',
 'Normal(172)',
 'Normal(172).jpg',
 'Normal(173)',
 'Normal(173).jpg',
 'Normal(174)',
 'Normal(174).jpg',
 'Normal(175)',
 'Normal(175).jpg',
 'Normal(176)',
 'Normal(176).jpg',
 'Normal(177)',
 'Normal(177).jpg',
 'Normal(178)',
 'Normal(178).jpg',
 'Normal(179)',
 'Normal(179).jpg',
 'Normal(18)',
 'Normal(18).jpg',
 'Normal(180)',
 'Normal(180).jpg',
 'Normal(181)',
 'Normal(181).jpg',
 'Normal(182)',
 'Normal(182).jpg',
 'Normal(183)',
 'Normal(183).jpg',
 'Normal(184)',
 'Normal(184).jpg',
 'Normal(185)',
 'Normal(185).jpg',
 'Normal(186)',
 'Normal(186).jpg',
 'Normal(187)',
 'Normal(187).jpg',
 'Normal(188)',
 'Normal(188).jpg',
 'Normal(189)',
 'Normal(189).jpg',
 'Normal(19)',
 'Normal(19).jpg',
 'Normal(190)',
 'Normal(190).jpg',
 'Normal(191)',
 'Normal(191).jpg',
 'Normal(192)',
 'Normal(192).jpg',
 'Normal(193)',
 'Normal(193).jpg',
 'Normal(194)',
 'Normal(194).jpg',
 'Normal(195)',
 'Normal(195).jpg',
 'Normal(196)',
 'Normal(196).jpg',
 'Normal(197)',
 'Normal(197).jpg',
 'Normal(198)',
 'Normal(198).jpg',
 'Normal(199)',
 'Normal(199).jpg',
 'Normal(2)',
 'Normal(2).jpg',
 'Normal(20)',
 'Normal(20).jpg',
 'Normal(200)',
 'Normal(200).jpg',
 'Normal(201)',
 'Normal(201).jpg',
 'Normal(202)',
 'Normal(202).jpg',
 'Normal(203)',
 'Normal(203).jpg',
 'Normal(204)',
 'Normal(204).jpg',
 'Normal(205)',
 'Normal(205).jpg',
 'Normal(206)',
 'Normal(206).jpg',
 'Normal(207)',
 'Normal(207).jpg',
 'Normal(208)',
 'Normal(208).jpg',
 'Normal(209)',
 'Normal(209).jpg',
 'Normal(21)',
 'Normal(21).jpg',
 'Normal(210)',
 'Normal(210).jpg',
 'Normal(211)',
 'Normal(211).jpg',
 'Normal(212)',
 'Normal(212).jpg',
 'Normal(213)',
 'Normal(213).jpg',
 'Normal(214)',
 'Normal(214).jpg',
 'Normal(215)',
 'Normal(215).jpg',
 'Normal(216)',
 'Normal(216).jpg',
 'Normal(217)',
 'Normal(217).jpg',
 'Normal(218)',
 'Normal(218).jpg',
 'Normal(219)',
 'Normal(219).jpg',
 'Normal(22)',
 'Normal(22).jpg',
 'Normal(220)',
 'Normal(220).jpg',
 'Normal(221)',
 'Normal(221).jpg',
 'Normal(222)',
 'Normal(222).jpg',
 'Normal(223)',
 'Normal(223).jpg',
 'Normal(224)',
 'Normal(224).jpg',
 'Normal(225)',
 'Normal(225).jpg',
 'Normal(226)',
 'Normal(226).jpg',
 'Normal(227)',
 'Normal(227).jpg',
 'Normal(228)',
 'Normal(228).jpg',
 'Normal(229)',
 'Normal(229).jpg',
 'Normal(23)',
 'Normal(23).jpg',
 'Normal(230)',
 'Normal(230).jpg',
 'Normal(231)',
 'Normal(231).jpg',
 'Normal(232)',
 'Normal(232).jpg',
 'Normal(233)',
 'Normal(233).jpg',
 'Normal(234)',
 'Normal(234).jpg',
 'Normal(235)',
 'Normal(235).jpg',
 'Normal(236)',
 'Normal(236).jpg',
 'Normal(237)',
 'Normal(237).jpg',
 'Normal(238)',
 'Normal(238).jpg',
 'Normal(239)',
 'Normal(239).jpg',
 'Normal(24)',
 'Normal(24).jpg',
 'Normal(240)',
 'Normal(240).jpg',
 'Normal(241)',
 'Normal(241).jpg',
 'Normal(242)',
 'Normal(242).jpg',
 'Normal(243)',
 'Normal(243).jpg',
 'Normal(244)',
 'Normal(244).jpg',
 'Normal(245)',
 'Normal(245).jpg',
 'Normal(246)',
 'Normal(246).jpg',
 'Normal(247)',
 'Normal(247).jpg',
 'Normal(248)',
 'Normal(248).jpg',
 'Normal(249)',
 'Normal(249).jpg',
 'Normal(25)',
 'Normal(25).jpg',
 'Normal(250)',
 'Normal(250).jpg',
 'Normal(251)',
 'Normal(251).jpg',
 'Normal(252)',
 'Normal(252).jpg',
 'Normal(253)',
 'Normal(253).jpg',
 'Normal(254)',
 'Normal(254).jpg',
 'Normal(255)',
 'Normal(255).jpg',
 'Normal(256)',
 'Normal(256).jpg',
 'Normal(257)',
 'Normal(257).jpg',
 'Normal(258)',
 'Normal(258).jpg',
 'Normal(259)',
 'Normal(259).jpg',
 'Normal(26)',
 'Normal(26).jpg',
 'Normal(260)',
 'Normal(260).jpg',
 'Normal(261)',
 'Normal(261).jpg',
 'Normal(262)',
 'Normal(262).jpg',
 'Normal(263)',
 'Normal(263).jpg',
 'Normal(264)',
 'Normal(264).jpg',
 'Normal(265)',
 'Normal(265).jpg',
 'Normal(266)',
 'Normal(266).jpg',
 'Normal(267)',
 'Normal(267).jpg',
 'Normal(268)',
 'Normal(268).jpg',
 'Normal(269)',
 'Normal(269).jpg',
 'Normal(27)',
 'Normal(27).jpg',
 'Normal(270)',
 'Normal(270).jpg',
 'Normal(271)',
 'Normal(271).jpg',
 'Normal(272)',
 'Normal(272).jpg',
 'Normal(273)',
 'Normal(273).jpg',
 'Normal(274)',
 'Normal(274).jpg',
 'Normal(275)',
 'Normal(275).jpg',
 'Normal(276)',
 'Normal(276).jpg',
 'Normal(277)',
 'Normal(277).jpg',
 'Normal(278)',
 'Normal(278).jpg',
 'Normal(279)',
 'Normal(279).jpg',
 'Normal(28)',
 'Normal(28).jpg',
 'Normal(280)',
 'Normal(280).jpg',
 'Normal(281)',
 'Normal(281).jpg',
 'Normal(282)',
 'Normal(282).jpg',
 'Normal(283)',
 'Normal(283).jpg',
 'Normal(284)',
 'Normal(284).jpg',
 'Normal(29)',
 'Normal(29).jpg',
 'Normal(3)',
 'Normal(3).jpg',
 'Normal(30)',
 'Normal(30).jpg',
 'Normal(31)',
 'Normal(31).jpg',
 'Normal(32)',
 'Normal(32).jpg',
 'Normal(33)',
 'Normal(33).jpg',
 'Normal(34)',
 'Normal(34).jpg',
 'Normal(35)',
 'Normal(35).jpg',
 'Normal(36)',
 'Normal(36).jpg',
 'Normal(37)',
 'Normal(37).jpg',
 'Normal(38)',
 'Normal(38).jpg',
 'Normal(39)',
 'Normal(39).jpg',
 'Normal(4)',
 'Normal(4).jpg',
 'Normal(40)',
 'Normal(40).jpg',
 'Normal(41)',
 'Normal(41).jpg',
 'Normal(42)',
 'Normal(42).jpg',
 'Normal(43)',
 'Normal(43).jpg',
 'Normal(44)',
 'Normal(44).jpg',
 'Normal(45)',
 'Normal(45).jpg',
 'Normal(46)',
 'Normal(46).jpg',
 'Normal(47)',
 'Normal(47).jpg',
 'Normal(48)',
 'Normal(48).jpg',
 'Normal(49)',
 'Normal(49).jpg',
 'Normal(5)',
 'Normal(5).jpg',
 'Normal(50)',
 'Normal(50).jpg',
 'Normal(51)',
 'Normal(51).jpg',
 'Normal(52)',
 'Normal(52).jpg',
 'Normal(53)',
 'Normal(53).jpg',
 'Normal(54)',
 'Normal(54).jpg',
 'Normal(55)',
 'Normal(55).jpg',
 'Normal(56)',
 'Normal(56).jpg',
 'Normal(57)',
 'Normal(57).jpg',
 'Normal(58)',
 'Normal(58).jpg',
 'Normal(59)',
 'Normal(59).jpg',
 'Normal(6)',
 'Normal(6).jpg',
 'Normal(60)',
 'Normal(60).jpg',
 'Normal(61)',
 'Normal(61).jpg',
 'Normal(62)',
 'Normal(62).jpg',
 'Normal(63)',
 'Normal(63).jpg',
 'Normal(64)',
 'Normal(64).jpg',
 'Normal(65)',
 'Normal(65).jpg',
 'Normal(66)',
 'Normal(66).jpg',
 'Normal(67)',
 'Normal(67).jpg',
 'Normal(68)',
 'Normal(68).jpg',
 'Normal(69)',
 'Normal(69).jpg',
 'Normal(7)',
 'Normal(7).jpg',
 'Normal(70)',
 'Normal(70).jpg',
 'Normal(71)',
 'Normal(71).jpg',
 'Normal(72)',
 'Normal(72).jpg',
 'Normal(73)',
 'Normal(73).jpg',
 'Normal(74)',
 'Normal(74).jpg',
 'Normal(75)',
 'Normal(75).jpg',
 'Normal(76)',
 'Normal(76).jpg',
 'Normal(77)',
 'Normal(77).jpg',
 'Normal(78)',
 'Normal(78).jpg',
 'Normal(79)',
 'Normal(79).jpg',
 'Normal(8)',
 'Normal(8).jpg',
 'Normal(80)',
 'Normal(80).jpg',
 'Normal(81)',
 'Normal(81).jpg',
 'Normal(82)',
 'Normal(82).jpg',
 'Normal(83)',
 'Normal(83).jpg',
 'Normal(84)',
 'Normal(84).jpg',
 'Normal(85)',
 'Normal(85).jpg',
 'Normal(86)',
 'Normal(86).jpg',
 'Normal(87)',
 'Normal(87).jpg',
 'Normal(88)',
 'Normal(88).jpg',
 'Normal(89)',
 'Normal(89).jpg',
 'Normal(9)',
 'Normal(9).jpg',
 'Normal(90)',
 'Normal(90).jpg',
 'Normal(91)',
 'Normal(91).jpg',
 'Normal(92)',
 'Normal(92).jpg',
 'Normal(93)',
 'Normal(93).jpg',
 'Normal(94)',
 'Normal(94).jpg',
 'Normal(95)',
 'Normal(95).jpg',
 'Normal(96)',
 'Normal(96).jpg',
 'Normal(97)',
 'Normal(97).jpg',
 'Normal(98)',
 'Normal(98).jpg',
 'Normal(99)',
 'Normal(99).jpg',
 'scaled_data_1D_1.csv',
 'scaled_data_1D_10.csv',
 'scaled_data_1D_11.csv',
 'scaled_data_1D_12.csv',
 'scaled_data_1D_13.csv',
 'scaled_data_1D_2.csv',
 'scaled_data_1D_3.csv',
 'scaled_data_1D_4.csv',
 'scaled_data_1D_5.csv',
 'scaled_data_1D_6.csv',
 'scaled_data_1D_7.csv',
 'scaled_data_1D_8.csv',
 'scaled_data_1D_9.csv']

In [5]:
MI_.sort()
MI_

['MI(1)',
 'MI(1).jpg',
 'MI(10)',
 'MI(10).jpg',
 'MI(100)',
 'MI(100).jpg',
 'MI(101)',
 'MI(101).jpg',
 'MI(102)',
 'MI(102).jpg',
 'MI(103)',
 'MI(103).jpg',
 'MI(104)',
 'MI(104).jpg',
 'MI(105)',
 'MI(105).jpg',
 'MI(106)',
 'MI(106).jpg',
 'MI(107)',
 'MI(107).jpg',
 'MI(108)',
 'MI(108).jpg',
 'MI(109)',
 'MI(109).jpg',
 'MI(11)',
 'MI(11).jpg',
 'MI(110)',
 'MI(110).jpg',
 'MI(111)',
 'MI(111).jpg',
 'MI(112)',
 'MI(112).jpg',
 'MI(113)',
 'MI(113).jpg',
 'MI(114)',
 'MI(114).jpg',
 'MI(115)',
 'MI(115).jpg',
 'MI(116)',
 'MI(116).jpg',
 'MI(117)',
 'MI(117).jpg',
 'MI(118)',
 'MI(118).jpg',
 'MI(119)',
 'MI(119).jpg',
 'MI(12)',
 'MI(12).jpg',
 'MI(120)',
 'MI(120).jpg',
 'MI(121)',
 'MI(121).jpg',
 'MI(122)',
 'MI(122).jpg',
 'MI(123)',
 'MI(123).jpg',
 'MI(124)',
 'MI(124).jpg',
 'MI(125)',
 'MI(125).jpg',
 'MI(126)',
 'MI(126).jpg',
 'MI(127)',
 'MI(127).jpg',
 'MI(128)',
 'MI(128).jpg',
 'MI(129)',
 'MI(129).jpg',
 'MI(13)',
 'MI(13).jpg',
 'MI(130)',
 'MI(130).jpg',
 'MI(131)',
 'MI(131).jpg',
 'MI(132)',
 'MI(132).jpg',
 'MI(133)',
 'MI(133).jpg',
 'MI(134)',
 'MI(134).jpg',
 'MI(135)',
 'MI(135).jpg',
 'MI(136)',
 'MI(136).jpg',
 'MI(137)',
 'MI(137).jpg',
 'MI(138)',
 'MI(138).jpg',
 'MI(139)',
 'MI(139).jpg',
 'MI(14)',
 'MI(14).jpg',
 'MI(140)',
 'MI(140).jpg',
 'MI(141)',
 'MI(141).jpg',
 'MI(142)',
 'MI(142).jpg',
 'MI(143)',
 'MI(143).jpg',
 'MI(144)',
 'MI(144).jpg',
 'MI(145)',
 'MI(145).jpg',
 'MI(146)',
 'MI(146).jpg',
 'MI(147)',
 'MI(147).jpg',
 'MI(148)',
 'MI(148).jpg',
 'MI(149)',
 'MI(149).jpg',
 'MI(15)',
 'MI(15).jpg',
 'MI(150)',
 'MI(150).jpg',
 'MI(151)',
 'MI(151).jpg',
 'MI(152)',
 'MI(152).jpg',
 'MI(153)',
 'MI(153).jpg',
 'MI(154)',
 'MI(154).jpg',
 'MI(155)',
 'MI(155).jpg',
 'MI(156)',
 'MI(156).jpg',
 'MI(157)',
 'MI(157).jpg',
 'MI(158)',
 'MI(158).jpg',
 'MI(159)',
 'MI(159).jpg',
 'MI(16)',
 'MI(16).jpg',
 'MI(160)',
 'MI(160).jpg',
 'MI(161)',
 'MI(161).jpg',
 'MI(162)',
 'MI(162).jpg',
 'MI(163)',
 'MI(163).jpg',
 'MI(164)',
 'MI(164).jpg',
 'MI(165)',
 'MI(165).jpg',
 'MI(166)',
 'MI(166).jpg',
 'MI(167)',
 'MI(167).jpg',
 'MI(168)',
 'MI(168).jpg',
 'MI(169)',
 'MI(169).jpg',
 'MI(17)',
 'MI(17).jpg',
 'MI(170)',
 'MI(170).jpg',
 'MI(171)',
 'MI(171).jpg',
 'MI(172)',
 'MI(172).jpg',
 'MI(173)',
 'MI(173).jpg',
 'MI(174)',
 'MI(174).jpg',
 'MI(175)',
 'MI(175).jpg',
 'MI(176)',
 'MI(176).jpg',
 'MI(177)',
 'MI(177).jpg',
 'MI(178)',
 'MI(178).jpg',
 'MI(179)',
 'MI(179).jpg',
 'MI(18)',
 'MI(18).jpg',
 'MI(180)',
 'MI(180).jpg',
 'MI(181)',
 'MI(181).jpg',
 'MI(182)',
 'MI(182).jpg',
 'MI(183)',
 'MI(183).jpg',
 'MI(184)',
 'MI(184).jpg',
 'MI(185)',
 'MI(185).jpg',
 'MI(186)',
 'MI(186).jpg',
 'MI(187)',
 'MI(187).jpg',
 'MI(188)',
 'MI(188).jpg',
 'MI(189)',
 'MI(189).jpg',
 'MI(19)',
 'MI(19).jpg',
 'MI(190)',
 'MI(190).jpg',
 'MI(191)',
 'MI(191).jpg',
 'MI(192)',
 'MI(192).jpg',
 'MI(193)',
 'MI(193).jpg',
 'MI(194)',
 'MI(194).jpg',
 'MI(195)',
 'MI(195).jpg',
 'MI(196)',
 'MI(196).jpg',
 'MI(197)',
 'MI(197).jpg',
 'MI(198)',
 'MI(198).jpg',
 'MI(199)',
 'MI(199).jpg',
 'MI(2)',
 'MI(2).jpg',
 'MI(20)',
 'MI(20).jpg',
 'MI(200)',
 'MI(200).jpg',
 'MI(201)',
 'MI(201).jpg',
 'MI(202)',
 'MI(202).jpg',
 'MI(203)',
 'MI(203).jpg',
 'MI(204)',
 'MI(204).jpg',
 'MI(205)',
 'MI(205).jpg',
 'MI(206)',
 'MI(206).jpg',
 'MI(207)',
 'MI(207).jpg',
 'MI(208)',
 'MI(208).jpg',
 'MI(209)',
 'MI(209).jpg',
 'MI(21)',
 'MI(21).jpg',
 'MI(210)',
 'MI(210).jpg',
 'MI(211)',
 'MI(211).jpg',
 'MI(212)',
 'MI(212).jpg',
 'MI(213)',
 'MI(213).jpg',
 'MI(214)',
 'MI(214).jpg',
 'MI(216)',
 'MI(216).jpg',
 'MI(217)',
 'MI(217).jpg',
 'MI(218)',
 'MI(218).jpg',
 'MI(219)',
 'MI(219).jpg',
 'MI(22)',
 'MI(22).jpg',
 'MI(220)',
 'MI(220).jpg',
 'MI(221)',
 'MI(221).jpg',
 'MI(222)',
 'MI(222).jpg',
 'MI(223)',
 'MI(223).jpg',
 'MI(224)',
 'MI(224).jpg',
 'MI(225)',
 'MI(225).jpg',
 'MI(226)',
 'MI(226).jpg',
 'MI(227)',
 'MI(227).jpg',
 'MI(228)',
 'MI(228).jpg',
 'MI(229)',
 'MI(229).jpg',
 'MI(23)',
 'MI(23).jpg',
 'MI(230)',
 'MI(230).jpg',
 'MI(231)',
 'MI(231).jpg',
 'MI(232)',
 'MI(232).jpg',
 'MI(233)',
 'MI(233).jpg',
 'MI(234)',
 'MI(234).jpg',
 'MI(235)',
 'MI(235).jpg',
 'MI(236)',
 'MI(236).jpg',
 'MI(237)',
 'MI(237).jpg',
 'MI(238)',
 'MI(238).jpg',
 'MI(239)',
 'MI(239).jpg',
 'MI(24)',
 'MI(24).jpg',
 'MI(240)',
 'MI(240).jpg',
 'MI(25)',
 'MI(25).jpg',
 'MI(26)',
 'MI(26).jpg',
 'MI(27)',
 'MI(27).jpg',
 'MI(28)',
 'MI(28).jpg',
 'MI(29)',
 'MI(29).jpg',
 'MI(3)',
 'MI(3).jpg',
 'MI(30)',
 'MI(30).jpg',
 'MI(31)',
 'MI(31).jpg',
 'MI(32)',
 'MI(32).jpg',
 'MI(33)',
 'MI(33).jpg',
 'MI(34)',
 'MI(34).jpg',
 'MI(35)',
 'MI(35).jpg',
 'MI(36)',
 'MI(36).jpg',
 'MI(37)',
 'MI(37).jpg',
 'MI(38)',
 'MI(38).jpg',
 'MI(39)',
 'MI(39).jpg',
 'MI(4)',
 'MI(4).jpg',
 'MI(40)',
 'MI(40).jpg',
 'MI(41)',
 'MI(41).jpg',
 'MI(42)',
 'MI(42).jpg',
 'MI(43)',
 'MI(43).jpg',
 'MI(44)',
 'MI(44).jpg',
 'MI(45)',
 'MI(45).jpg',
 'MI(46)',
 'MI(46).jpg',
 'MI(47)',
 'MI(47).jpg',
 'MI(48)',
 'MI(48).jpg',
 'MI(49)',
 'MI(49).jpg',
 'MI(5)',
 'MI(5).jpg',
 'MI(50)',
 'MI(50).jpg',
 'MI(51)',
 'MI(51).jpg',
 'MI(52)',
 'MI(52).jpg',
 'MI(53)',
 'MI(53).jpg',
 'MI(54)',
 'MI(54).jpg',
 'MI(55)',
 'MI(55).jpg',
 'MI(56)',
 'MI(56).jpg',
 'MI(57)',
 'MI(57).jpg',
 'MI(58)',
 'MI(58).jpg',
 'MI(59)',
 'MI(59).jpg',
 'MI(6)',
 'MI(6).jpg',
 'MI(60)',
 'MI(60).jpg',
 'MI(61)',
 'MI(61).jpg',
 'MI(62)',
 'MI(62).jpg',
 'MI(63)',
 'MI(63).jpg',
 'MI(64)',
 'MI(64).jpg',
 'MI(65)',
 'MI(65).jpg',
 'MI(66)',
 'MI(66).jpg',
 'MI(67)',
 'MI(67).jpg',
 'MI(68)',
 'MI(68).jpg',
 'MI(69)',
 'MI(69).jpg',
 'MI(7)',
 'MI(7).jpg',
 'MI(70)',
 'MI(70).jpg',
 'MI(71)',
 'MI(71).jpg',
 'MI(72)',
 'MI(72).jpg',
 'MI(73)',
 'MI(73).jpg',
 'MI(74)',
 'MI(74).jpg',
 'MI(75)',
 'MI(75).jpg',
 'MI(76)',
 'MI(76).jpg',
 'MI(77)',
 'MI(77).jpg',
 'MI(78)',
 'MI(78).jpg',
 'MI(79)',
 'MI(79).jpg',
 'MI(8)',
 'MI(8).jpg',
 'MI(80)',
 'MI(80).jpg',
 'MI(81)',
 'MI(81).jpg',
 'MI(82)',
 'MI(82).jpg',
 'MI(83)',
 'MI(83).jpg',
 'MI(84)',
 'MI(84).jpg',
 'MI(85)',
 'MI(85).jpg',
 'MI(86)',
 'MI(86).jpg',
 'MI(87)',
 'MI(87).jpg',
 'MI(88)',
 'MI(88).jpg',
 'MI(89)',
 'MI(89).jpg',
 'MI(9)',
 'MI(9).jpg',
 'MI(90)',
 'MI(90).jpg',
 'MI(91)',
 'MI(91).jpg',
 'MI(92)',
 'MI(92).jpg',
 'MI(93)',
 'MI(93).jpg',
 'MI(94)',
 'MI(94).jpg',
 'MI(95)',
 'MI(95).jpg',
 'MI(96)',
 'MI(96).jpg',
 'MI(97)',
 'MI(97).jpg',
 'MI(98)',
 'MI(98).jpg',
 'MI(99)',
 'MI(99).jpg',
 'scaled_data_1D_1.csv',
 'scaled_data_1D_10.csv',
 'scaled_data_1D_11.csv',
 'scaled_data_1D_12.csv',
 'scaled_data_1D_13.csv',
 'scaled_data_1D_2.csv',
 'scaled_data_1D_3.csv',
 'scaled_data_1D_4.csv',
 'scaled_data_1D_5.csv',
 'scaled_data_1D_6.csv',
 'scaled_data_1D_7.csv',
 'scaled_data_1D_8.csv',
 'scaled_data_1D_9.csv']

In [6]:
PMI_.sort()
PMI_

['PMI(1)',
 'PMI(1).jpg',
 'PMI(10)',
 'PMI(10).jpg',
 'PMI(100)',
 'PMI(100).jpg',
 'PMI(101)',
 'PMI(101).jpg',
 'PMI(102)',
 'PMI(102).jpg',
 'PMI(103)',
 'PMI(103).jpg',
 'PMI(104)',
 'PMI(104).jpg',
 'PMI(105)',
 'PMI(105).jpg',
 'PMI(106)',
 'PMI(106).jpg',
 'PMI(107)',
 'PMI(107).jpg',
 'PMI(108)',
 'PMI(108).jpg',
 'PMI(109)',
 'PMI(109).jpg',
 'PMI(11)',
 'PMI(11).jpg',
 'PMI(110)',
 'PMI(110).jpg',
 'PMI(111)',
 'PMI(111).jpg',
 'PMI(112)',
 'PMI(112).jpg',
 'PMI(113)',
 'PMI(113).jpg',
 'PMI(114)',
 'PMI(114).jpg',
 'PMI(115)',
 'PMI(115).jpg',
 'PMI(116)',
 'PMI(116).jpg',
 'PMI(117)',
 'PMI(117).jpg',
 'PMI(118)',
 'PMI(118).jpg',
 'PMI(119)',
 'PMI(119).jpg',
 'PMI(12)',
 'PMI(12).jpg',
 'PMI(120)',
 'PMI(120).jpg',
 'PMI(121)',
 'PMI(121).jpg',
 'PMI(122)',
 'PMI(122).jpg',
 'PMI(123)',
 'PMI(123).jpg',
 'PMI(124)',
 'PMI(124).jpg',
 'PMI(125)',
 'PMI(125).jpg',
 'PMI(126)',
 'PMI(126).jpg',
 'PMI(127)',
 'PMI(127).jpg',
 'PMI(128)',
 'PMI(128).jpg',
 'PMI(129)',
 'PMI(129).jpg',
 'PMI(13)',
 'PMI(13).jpg',
 'PMI(130)',
 'PMI(130).jpg',
 'PMI(131)',
 'PMI(131).jpg',
 'PMI(132)',
 'PMI(132).jpg',
 'PMI(133)',
 'PMI(133).jpg',
 'PMI(134)',
 'PMI(134).jpg',
 'PMI(135)',
 'PMI(135).jpg',
 'PMI(136)',
 'PMI(136).jpg',
 'PMI(137)',
 'PMI(137).jpg',
 'PMI(138)',
 'PMI(138).jpg',
 'PMI(139)',
 'PMI(139).jpg',
 'PMI(14)',
 'PMI(14).jpg',
 'PMI(140)',
 'PMI(140).jpg',
 'PMI(141)',
 'PMI(141).jpg',
 'PMI(142)',
 'PMI(142).jpg',
 'PMI(143)',
 'PMI(143).jpg',
 'PMI(144)',
 'PMI(144).jpg',
 'PMI(145)',
 'PMI(145).jpg',
 'PMI(146)',
 'PMI(146).jpg',
 'PMI(147)',
 'PMI(147).jpg',
 'PMI(148)',
 'PMI(148).jpg',
 'PMI(149)',
 'PMI(149).jpg',
 'PMI(15)',
 'PMI(15).jpg',
 'PMI(150)',
 'PMI(150).jpg',
 'PMI(151)',
 'PMI(151).jpg',
 'PMI(152)',
 'PMI(152).jpg',
 'PMI(153)',
 'PMI(153).jpg',
 'PMI(154)',
 'PMI(154).jpg',
 'PMI(155)',
 'PMI(155).jpg',
 'PMI(156)',
 'PMI(156).jpg',
 'PMI(157)',
 'PMI(157).jpg',
 'PMI(158)',
 'PMI(158).jpg',
 'PMI(159)',
 'PMI(159).jpg',
 'PMI(16)',
 'PMI(16).jpg',
 'PMI(160)',
 'PMI(160).jpg',
 'PMI(161)',
 'PMI(161).jpg',
 'PMI(162)',
 'PMI(162).jpg',
 'PMI(163)',
 'PMI(163).jpg',
 'PMI(164)',
 'PMI(164).jpg',
 'PMI(165)',
 'PMI(165).jpg',
 'PMI(166)',
 'PMI(166).jpg',
 'PMI(167)',
 'PMI(167).jpg',
 'PMI(168)',
 'PMI(168).jpg',
 'PMI(169)',
 'PMI(169).jpg',
 'PMI(17)',
 'PMI(17).jpg',
 'PMI(170)',
 'PMI(170).jpg',
 'PMI(171)',
 'PMI(171).jpg',
 'PMI(172)',
 'PMI(172).jpg',
 'PMI(18)',
 'PMI(18).jpg',
 'PMI(19)',
 'PMI(19).jpg',
 'PMI(2)',
 'PMI(2).jpg',
 'PMI(20)',
 'PMI(20).jpg',
 'PMI(21)',
 'PMI(21).jpg',
 'PMI(22)',
 'PMI(22).jpg',
 'PMI(23)',
 'PMI(23).jpg',
 'PMI(24)',
 'PMI(24).jpg',
 'PMI(25)',
 'PMI(25).jpg',
 'PMI(26)',
 'PMI(26).jpg',
 'PMI(27)',
 'PMI(27).jpg',
 'PMI(28)',
 'PMI(28).jpg',
 'PMI(29)',
 'PMI(29).jpg',
 'PMI(3)',
 'PMI(3).jpg',
 'PMI(30)',
 'PMI(30).jpg',
 'PMI(31)',
 'PMI(31).jpg',
 'PMI(32)',
 'PMI(32).jpg',
 'PMI(33)',
 'PMI(33).jpg',
 'PMI(34)',
 'PMI(34).jpg',
 'PMI(35)',
 'PMI(35).jpg',
 'PMI(36)',
 'PMI(36).jpg',
 'PMI(37)',
 'PMI(37).jpg',
 'PMI(38)',
 'PMI(38).jpg',
 'PMI(39)',
 'PMI(39).jpg',
 'PMI(4)',
 'PMI(4).jpg',
 'PMI(40)',
 'PMI(40).jpg',
 'PMI(41)',
 'PMI(41).jpg',
 'PMI(42)',
 'PMI(42).jpg',
 'PMI(43)',
 'PMI(43).jpg',
 'PMI(44)',
 'PMI(44).jpg',
 'PMI(45)',
 'PMI(45).jpg',
 'PMI(46)',
 'PMI(46).jpg',
 'PMI(47)',
 'PMI(47).jpg',
 'PMI(48)',
 'PMI(48).jpg',
 'PMI(49)',
 'PMI(49).jpg',
 'PMI(5)',
 'PMI(5).jpg',
 'PMI(50)',
 'PMI(50).jpg',
 'PMI(51)',
 'PMI(51).jpg',
 'PMI(52)',
 'PMI(52).jpg',
 'PMI(53)',
 'PMI(53).jpg',
 'PMI(54)',
 'PMI(54).jpg',
 'PMI(55)',
 'PMI(55).jpg',
 'PMI(56)',
 'PMI(56).jpg',
 'PMI(57)',
 'PMI(57).jpg',
 'PMI(58)',
 'PMI(58).jpg',
 'PMI(59)',
 'PMI(59).jpg',
 'PMI(6)',
 'PMI(6).jpg',
 'PMI(60)',
 'PMI(60).jpg',
 'PMI(61)',
 'PMI(61).jpg',
 'PMI(62)',
 'PMI(62).jpg',
 'PMI(63)',
 'PMI(63).jpg',
 'PMI(64)',
 'PMI(64).jpg',
 'PMI(65)',
 'PMI(65).jpg',
 'PMI(66)',
 'PMI(66).jpg',
 'PMI(67)',
 'PMI(67).jpg',
 'PMI(68)',
 'PMI(68).jpg',
 'PMI(69)',
 'PMI(69).jpg',
 'PMI(7)',
 'PMI(7).jpg',
 'PMI(70)',
 'PMI(70).jpg',
 'PMI(71)',
 'PMI(71).jpg',
 'PMI(72)',
 'PMI(72).jpg',
 'PMI(73)',
 'PMI(73).jpg',
 'PMI(74)',
 'PMI(74).jpg',
 'PMI(75)',
 'PMI(75).jpg',
 'PMI(76)',
 'PMI(76).jpg',
 'PMI(77)',
 'PMI(77).jpg',
 'PMI(78)',
 'PMI(78).jpg',
 'PMI(79)',
 'PMI(79).jpg',
 'PMI(8)',
 'PMI(8).jpg',
 'PMI(80)',
 'PMI(80).jpg',
 'PMI(81)',
 'PMI(81).jpg',
 'PMI(82)',
 'PMI(82).jpg',
 'PMI(83)',
 'PMI(83).jpg',
 'PMI(84)',
 'PMI(84).jpg',
 'PMI(85)',
 'PMI(85).jpg',
 'PMI(86)',
 'PMI(86).jpg',
 'PMI(87)',
 'PMI(87).jpg',
 'PMI(88)',
 'PMI(88).jpg',
 'PMI(89)',
 'PMI(89).jpg',
 'PMI(9)',
 'PMI(9).jpg',
 'PMI(90)',
 'PMI(90).jpg',
 'PMI(91)',
 'PMI(91).jpg',
 'PMI(92)',
 'PMI(92).jpg',
 'PMI(93)',
 'PMI(93).jpg',
 'PMI(94)',
 'PMI(94).jpg',
 'PMI(95)',
 'PMI(95).jpg',
 'PMI(96)',
 'PMI(96).jpg',
 'PMI(97)',
 'PMI(97).jpg',
 'PMI(98)',
 'PMI(98).jpg',
 'PMI(99)',
 'PMI(99).jpg',
 'scaled_data_1D_1.csv',
 'scaled_data_1D_10.csv',
 'scaled_data_1D_11.csv',
 'scaled_data_1D_12.csv',
 'scaled_data_1D_13.csv',
 'scaled_data_1D_2.csv',
 'scaled_data_1D_3.csv',
 'scaled_data_1D_4.csv',
 'scaled_data_1D_5.csv',
 'scaled_data_1D_6.csv',
 'scaled_data_1D_7.csv',
 'scaled_data_1D_8.csv',
 'scaled_data_1D_9.csv']

In [7]:
MI_.sort()
MI_

['MI(1)',
 'MI(1).jpg',
 'MI(10)',
 'MI(10).jpg',
 'MI(100)',
 'MI(100).jpg',
 'MI(101)',
 'MI(101).jpg',
 'MI(102)',
 'MI(102).jpg',
 'MI(103)',
 'MI(103).jpg',
 'MI(104)',
 'MI(104).jpg',
 'MI(105)',
 'MI(105).jpg',
 'MI(106)',
 'MI(106).jpg',
 'MI(107)',
 'MI(107).jpg',
 'MI(108)',
 'MI(108).jpg',
 'MI(109)',
 'MI(109).jpg',
 'MI(11)',
 'MI(11).jpg',
 'MI(110)',
 'MI(110).jpg',
 'MI(111)',
 'MI(111).jpg',
 'MI(112)',
 'MI(112).jpg',
 'MI(113)',
 'MI(113).jpg',
 'MI(114)',
 'MI(114).jpg',
 'MI(115)',
 'MI(115).jpg',
 'MI(116)',
 'MI(116).jpg',
 'MI(117)',
 'MI(117).jpg',
 'MI(118)',
 'MI(118).jpg',
 'MI(119)',
 'MI(119).jpg',
 'MI(12)',
 'MI(12).jpg',
 'MI(120)',
 'MI(120).jpg',
 'MI(121)',
 'MI(121).jpg',
 'MI(122)',
 'MI(122).jpg',
 'MI(123)',
 'MI(123).jpg',
 'MI(124)',
 'MI(124).jpg',
 'MI(125)',
 'MI(125).jpg',
 'MI(126)',
 'MI(126).jpg',
 'MI(127)',
 'MI(127).jpg',
 'MI(128)',
 'MI(128).jpg',
 'MI(129)',
 'MI(129).jpg',
 'MI(13)',
 'MI(13).jpg',
 'MI(130)',
 'MI(130).jpg',
 'MI(131)',
 'MI(131).jpg',
 'MI(132)',
 'MI(132).jpg',
 'MI(133)',
 'MI(133).jpg',
 'MI(134)',
 'MI(134).jpg',
 'MI(135)',
 'MI(135).jpg',
 'MI(136)',
 'MI(136).jpg',
 'MI(137)',
 'MI(137).jpg',
 'MI(138)',
 'MI(138).jpg',
 'MI(139)',
 'MI(139).jpg',
 'MI(14)',
 'MI(14).jpg',
 'MI(140)',
 'MI(140).jpg',
 'MI(141)',
 'MI(141).jpg',
 'MI(142)',
 'MI(142).jpg',
 'MI(143)',
 'MI(143).jpg',
 'MI(144)',
 'MI(144).jpg',
 'MI(145)',
 'MI(145).jpg',
 'MI(146)',
 'MI(146).jpg',
 'MI(147)',
 'MI(147).jpg',
 'MI(148)',
 'MI(148).jpg',
 'MI(149)',
 'MI(149).jpg',
 'MI(15)',
 'MI(15).jpg',
 'MI(150)',
 'MI(150).jpg',
 'MI(151)',
 'MI(151).jpg',
 'MI(152)',
 'MI(152).jpg',
 'MI(153)',
 'MI(153).jpg',
 'MI(154)',
 'MI(154).jpg',
 'MI(155)',
 'MI(155).jpg',
 'MI(156)',
 'MI(156).jpg',
 'MI(157)',
 'MI(157).jpg',
 'MI(158)',
 'MI(158).jpg',
 'MI(159)',
 'MI(159).jpg',
 'MI(16)',
 'MI(16).jpg',
 'MI(160)',
 'MI(160).jpg',
 'MI(161)',
 'MI(161).jpg',
 'MI(162)',
 'MI(162).jpg',
 'MI(163)',
 'MI(163).jpg',
 'MI(164)',
 'MI(164).jpg',
 'MI(165)',
 'MI(165).jpg',
 'MI(166)',
 'MI(166).jpg',
 'MI(167)',
 'MI(167).jpg',
 'MI(168)',
 'MI(168).jpg',
 'MI(169)',
 'MI(169).jpg',
 'MI(17)',
 'MI(17).jpg',
 'MI(170)',
 'MI(170).jpg',
 'MI(171)',
 'MI(171).jpg',
 'MI(172)',
 'MI(172).jpg',
 'MI(173)',
 'MI(173).jpg',
 'MI(174)',
 'MI(174).jpg',
 'MI(175)',
 'MI(175).jpg',
 'MI(176)',
 'MI(176).jpg',
 'MI(177)',
 'MI(177).jpg',
 'MI(178)',
 'MI(178).jpg',
 'MI(179)',
 'MI(179).jpg',
 'MI(18)',
 'MI(18).jpg',
 'MI(180)',
 'MI(180).jpg',
 'MI(181)',
 'MI(181).jpg',
 'MI(182)',
 'MI(182).jpg',
 'MI(183)',
 'MI(183).jpg',
 'MI(184)',
 'MI(184).jpg',
 'MI(185)',
 'MI(185).jpg',
 'MI(186)',
 'MI(186).jpg',
 'MI(187)',
 'MI(187).jpg',
 'MI(188)',
 'MI(188).jpg',
 'MI(189)',
 'MI(189).jpg',
 'MI(19)',
 'MI(19).jpg',
 'MI(190)',
 'MI(190).jpg',
 'MI(191)',
 'MI(191).jpg',
 'MI(192)',
 'MI(192).jpg',
 'MI(193)',
 'MI(193).jpg',
 'MI(194)',
 'MI(194).jpg',
 'MI(195)',
 'MI(195).jpg',
 'MI(196)',
 'MI(196).jpg',
 'MI(197)',
 'MI(197).jpg',
 'MI(198)',
 'MI(198).jpg',
 'MI(199)',
 'MI(199).jpg',
 'MI(2)',
 'MI(2).jpg',
 'MI(20)',
 'MI(20).jpg',
 'MI(200)',
 'MI(200).jpg',
 'MI(201)',
 'MI(201).jpg',
 'MI(202)',
 'MI(202).jpg',
 'MI(203)',
 'MI(203).jpg',
 'MI(204)',
 'MI(204).jpg',
 'MI(205)',
 'MI(205).jpg',
 'MI(206)',
 'MI(206).jpg',
 'MI(207)',
 'MI(207).jpg',
 'MI(208)',
 'MI(208).jpg',
 'MI(209)',
 'MI(209).jpg',
 'MI(21)',
 'MI(21).jpg',
 'MI(210)',
 'MI(210).jpg',
 'MI(211)',
 'MI(211).jpg',
 'MI(212)',
 'MI(212).jpg',
 'MI(213)',
 'MI(213).jpg',
 'MI(214)',
 'MI(214).jpg',
 'MI(216)',
 'MI(216).jpg',
 'MI(217)',
 'MI(217).jpg',
 'MI(218)',
 'MI(218).jpg',
 'MI(219)',
 'MI(219).jpg',
 'MI(22)',
 'MI(22).jpg',
 'MI(220)',
 'MI(220).jpg',
 'MI(221)',
 'MI(221).jpg',
 'MI(222)',
 'MI(222).jpg',
 'MI(223)',
 'MI(223).jpg',
 'MI(224)',
 'MI(224).jpg',
 'MI(225)',
 'MI(225).jpg',
 'MI(226)',
 'MI(226).jpg',
 'MI(227)',
 'MI(227).jpg',
 'MI(228)',
 'MI(228).jpg',
 'MI(229)',
 'MI(229).jpg',
 'MI(23)',
 'MI(23).jpg',
 'MI(230)',
 'MI(230).jpg',
 'MI(231)',
 'MI(231).jpg',
 'MI(232)',
 'MI(232).jpg',
 'MI(233)',
 'MI(233).jpg',
 'MI(234)',
 'MI(234).jpg',
 'MI(235)',
 'MI(235).jpg',
 'MI(236)',
 'MI(236).jpg',
 'MI(237)',
 'MI(237).jpg',
 'MI(238)',
 'MI(238).jpg',
 'MI(239)',
 'MI(239).jpg',
 'MI(24)',
 'MI(24).jpg',
 'MI(240)',
 'MI(240).jpg',
 'MI(25)',
 'MI(25).jpg',
 'MI(26)',
 'MI(26).jpg',
 'MI(27)',
 'MI(27).jpg',
 'MI(28)',
 'MI(28).jpg',
 'MI(29)',
 'MI(29).jpg',
 'MI(3)',
 'MI(3).jpg',
 'MI(30)',
 'MI(30).jpg',
 'MI(31)',
 'MI(31).jpg',
 'MI(32)',
 'MI(32).jpg',
 'MI(33)',
 'MI(33).jpg',
 'MI(34)',
 'MI(34).jpg',
 'MI(35)',
 'MI(35).jpg',
 'MI(36)',
 'MI(36).jpg',
 'MI(37)',
 'MI(37).jpg',
 'MI(38)',
 'MI(38).jpg',
 'MI(39)',
 'MI(39).jpg',
 'MI(4)',
 'MI(4).jpg',
 'MI(40)',
 'MI(40).jpg',
 'MI(41)',
 'MI(41).jpg',
 'MI(42)',
 'MI(42).jpg',
 'MI(43)',
 'MI(43).jpg',
 'MI(44)',
 'MI(44).jpg',
 'MI(45)',
 'MI(45).jpg',
 'MI(46)',
 'MI(46).jpg',
 'MI(47)',
 'MI(47).jpg',
 'MI(48)',
 'MI(48).jpg',
 'MI(49)',
 'MI(49).jpg',
 'MI(5)',
 'MI(5).jpg',
 'MI(50)',
 'MI(50).jpg',
 'MI(51)',
 'MI(51).jpg',
 'MI(52)',
 'MI(52).jpg',
 'MI(53)',
 'MI(53).jpg',
 'MI(54)',
 'MI(54).jpg',
 'MI(55)',
 'MI(55).jpg',
 'MI(56)',
 'MI(56).jpg',
 'MI(57)',
 'MI(57).jpg',
 'MI(58)',
 'MI(58).jpg',
 'MI(59)',
 'MI(59).jpg',
 'MI(6)',
 'MI(6).jpg',
 'MI(60)',
 'MI(60).jpg',
 'MI(61)',
 'MI(61).jpg',
 'MI(62)',
 'MI(62).jpg',
 'MI(63)',
 'MI(63).jpg',
 'MI(64)',
 'MI(64).jpg',
 'MI(65)',
 'MI(65).jpg',
 'MI(66)',
 'MI(66).jpg',
 'MI(67)',
 'MI(67).jpg',
 'MI(68)',
 'MI(68).jpg',
 'MI(69)',
 'MI(69).jpg',
 'MI(7)',
 'MI(7).jpg',
 'MI(70)',
 'MI(70).jpg',
 'MI(71)',
 'MI(71).jpg',
 'MI(72)',
 'MI(72).jpg',
 'MI(73)',
 'MI(73).jpg',
 'MI(74)',
 'MI(74).jpg',
 'MI(75)',
 'MI(75).jpg',
 'MI(76)',
 'MI(76).jpg',
 'MI(77)',
 'MI(77).jpg',
 'MI(78)',
 'MI(78).jpg',
 'MI(79)',
 'MI(79).jpg',
 'MI(8)',
 'MI(8).jpg',
 'MI(80)',
 'MI(80).jpg',
 'MI(81)',
 'MI(81).jpg',
 'MI(82)',
 'MI(82).jpg',
 'MI(83)',
 'MI(83).jpg',
 'MI(84)',
 'MI(84).jpg',
 'MI(85)',
 'MI(85).jpg',
 'MI(86)',
 'MI(86).jpg',
 'MI(87)',
 'MI(87).jpg',
 'MI(88)',
 'MI(88).jpg',
 'MI(89)',
 'MI(89).jpg',
 'MI(9)',
 'MI(9).jpg',
 'MI(90)',
 'MI(90).jpg',
 'MI(91)',
 'MI(91).jpg',
 'MI(92)',
 'MI(92).jpg',
 'MI(93)',
 'MI(93).jpg',
 'MI(94)',
 'MI(94).jpg',
 'MI(95)',
 'MI(95).jpg',
 'MI(96)',
 'MI(96).jpg',
 'MI(97)',
 'MI(97).jpg',
 'MI(98)',
 'MI(98).jpg',
 'MI(99)',
 'MI(99).jpg',
 'scaled_data_1D_1.csv',
 'scaled_data_1D_10.csv',
 'scaled_data_1D_11.csv',
 'scaled_data_1D_12.csv',
 'scaled_data_1D_13.csv',
 'scaled_data_1D_2.csv',
 'scaled_data_1D_3.csv',
 'scaled_data_1D_4.csv',
 'scaled_data_1D_5.csv',
 'scaled_data_1D_6.csv',
 'scaled_data_1D_7.csv',
 'scaled_data_1D_8.csv',
 'scaled_data_1D_9.csv']

#### **COMBINED CSV OF EACH LEAD(1-12) FROM ALL IMAGES**

In [27]:
# #loop over and create combined csv files for each leads.
# for x in range(len(MI_)):
#   df1=pd.read_csv('/content/drive/MyDrive/Cardiovascular-Detection-using-ECG-images-main/preprocessed_1d/NORMAL')
#   df2=pd.read_csv('/content/drive/MyDrive/Cardiovascular-Detection-using-ECG-images-main/preprocessed_1d/AHB')
#   df3=pd.read_csv('/content/drive/MyDrive/Cardiovascular-Detection-using-ECG-images-main/preprocessed_1d/MI')
#   df4=pd.read_csv('/content/drive/MyDrive/Cardiovascular-Detection-using-ECG-images-main/preprocessed_1d/PM')
#   final_df = pd.concat([df1,df2,df3,df4],ignore_index=True)
#   final_df.to_csv('/content/drive/MyDrive/CMPE255_PROJECT/Combined_IDLead_{}.csv'.format(x+1))
import pandas as pd
import os

# Assuming NORMAL_, AHB_, MI_, and PM_ are lists of file names
NORMAL_ = ["scaled_data_1D_1.csv", "scaled_data_1D_2.csv", "scaled_data_1D_3.csv", "scaled_data_1D_4.csv", "scaled_data_1D_5.csv"]  # Example file names
AHB_ = ["scaled_data_1D_1.csv", "scaled_data_1D_2.csv", "scaled_data_1D_3.csv","scaled_data_1D_4.csv", "scaled_data_1D_5.csv"]
MI_ = ["scaled_data_1D_1.csv", "scaled_data_1D_2.csv", "scaled_data_1D_3.csv","scaled_data_1D_4.csv","scaled_data_1D_5.csv"]
PM_ = ["scaled_data_1D_1.csv", "scaled_data_1D_2.csv", "scaled_data_1D_3.csv", "scaled_data_1D_4.csv", "scaled_data_1D_5.csv"]

# Define the base directory
base_dir = '/content/drive/MyDrive/Cardiovascular-Detection-using-ECG-images-main/preprocessed_1d'

import os


    # Loop over and create combined CSV files for each lead.
for x in range(len(MI_)):
    # Construct file paths
    df1_path = os.path.join(base_dir, 'NORMAL', NORMAL_[x])
    df2_path = os.path.join(base_dir, 'AHB', AHB_[x])
    df3_path = os.path.join(base_dir, 'MI', MI_[x])
    df4_path = os.path.join(base_dir, 'PM', PM_[x])

    # Read the CSV files
    df1 = pd.read_csv(df1_path)
    df2 = pd.read_csv(df2_path)
    df3 = pd.read_csv(df3_path)
    df4 = pd.read_csv(df4_path)

    # Combine the dataframes
    final_df = pd.concat([df1, df2, df3, df4], ignore_index=True)

    # Create the directory if it doesn't exist
    csv_folder_path = '/content/drive/MyDrive/CSV_files_folder'
    if not os.path.exists(csv_folder_path):
        os.makedirs(csv_folder_path)

    # # Save the combined dataframe
    # final_df.to_csv(f'/content/drive/MyDrive/CSV_files_folder/Combined_IDLead_{x+1}.csv', index=False)
    # Save the combined dataframe
    final_df.to_csv(f'{csv_folder_path}/Combined_IDLead_{x+1}.csv', index=False)

In [28]:
#now reading just lead1
df=pd.read_csv('/content/drive/MyDrive/CSV_files_folder/Combined_IDLead_1.csv')
df['Target'].unique()

array(['No', 'HB', 'MI', 'PM'], dtype=object)

In [31]:
df.drop(columns=['0'],inplace=True)
# print(df.columns)

In [32]:
#convert Target column values as Numeric using ngroups
encode_target_label = df.groupby('Target').ngroup().rename("target").to_frame()
test_final  = df.merge(encode_target_label, left_index=True, right_index=True)
test_final.drop(columns=['Target'],inplace=True)
test_final

,1,2,3,4,5,6,7,8,9,10,...,246,247,248,249,250,251,252,253,254,target
0,0.680755,0.619010,0.645367,0.681570,0.732488,0.758448,0.750660,0.728282,0.707928,0.710137,...,0.637260,0.664539,0.667226,0.637064,0.593287,0.545503,0.515049,0.563257,0.633581,2
1,0.950695,0.941024,0.930501,0.913601,0.892244,0.868016,0.855127,0.835307,0.798640,0.733188,...,0.778790,0.806883,0.818640,0.842472,0.866740,0.884152,0.897196,0.911293,0.922903,2
2,0.661575,0.695790,0.741113,0.716666,0.595794,0.425022,0.286457,0.425022,0.611384,0.775065,...,0.000000,0.042690,0.165850,0.363445,0.549460,0.539346,0.522272,0.491668,0.454949,2
3,0.861690,0.866457,0.865756,0.855027,0.855606,0.845561,0.843187,0.846784,0.824438,0.788354,...,0.789156,0.793622,0.787665,0.794515,0.796739,0.804063,0.809944,0.801814,0.777322,2
4,0.924369,0.873765,0.791381,0.699513,0.604927,0.500312,0.446012,0.528910,0.634068,0.732402,...,0.200676,0.300147,0.407225,0.507346,0.605953,0.699309,0.790334,0.856593,0.849957,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,0.877014,0.864280,0.860505,0.871349,0.912404,0.958148,0.977826,0.956314,0.926773,0.906898,...,0.908312,0.926328,0.898749,0.855709,0.823132,0.815458,0.818083,0.829300,0.822382,3
924,0.832084,0.852396,0.909665,0.988242,1.000000,0.923323,0.821865,0.721302,0.612039,0.544501,...,0.429721,0.531567,0.642137,0.742063,0.833042,0.814867,0.777622,0.760714,0.759294,3
925,0.417983,0.362322,0.351995,0.391493,0.418305,0.440135,0.444598,0.460402,0.506810,0.582590,...,0.408587,0.401864,0.387069,0.359590,0.325879,0.288894,0.293521,0.344504,0.399012,3
926,0.682286,0.641051,0.620212,0.608210,0.576331,0.603596,0.645714,0.677964,0.720297,0.727853,...,0.452247,0.450421,0.439278,0.439086,0.394417,0.441650,0.473909,0.539199,0.547146,3
927,0.815695,0.819518,0.820559,0.847985,0.880933,0.902061,0.878266,0.838806,0.811795,0.790403,...,0.737351,0.778845,0.805446,0.782640,0.751236,0.741331,0.718790,0.714504,0.691004,3

#### **PERFORM DIMENSIONALITY REDUCTION JUST FOR CHECKING/UNDERSTANDING**

In [33]:
#just for testing
# Now Perform Dimensionality reduction (PCA) on that Dataframe and check
from sklearn.decomposition import PCA

#do PCA and choose componeents as 100
pca = PCA(n_components=100)
x_pca = pca.fit_transform(test_final.iloc[:,0:-1])
x_pca = pd.DataFrame(x_pca)

# Calculate the variance explained by priciple components
explained_variance = pca.explained_variance_ratio_
print('Variance of each component:', pca.explained_variance_ratio_)
print('\n Total Variance Explained:', round(sum(list(pca.explained_variance_ratio_))*100, 2))

#store the new pca generated dimensions in a dataframe
pca_df = pd.DataFrame(data = x_pca)
target = pd.Series(test_final['target'], name='target')
result_df = pd.concat([pca_df, target], axis=1)
result_df

Variance of each component: [1.75512000e-01 9.51717081e-02 7.00586971e-02 6.16896147e-02
 5.35824886e-02 4.24590210e-02 3.69125660e-02 3.39226581e-02
 3.01447772e-02 2.90846036e-02 2.64993866e-02 2.42405202e-02
 2.10430516e-02 2.00021185e-02 1.77518640e-02 1.63355604e-02
 1.54159900e-02 1.48691091e-02 1.33657367e-02 1.19436183e-02
 1.16564576e-02 1.06031892e-02 9.70941925e-03 9.47275648e-03
 8.66939563e-03 8.49096885e-03 7.94649717e-03 7.30895723e-03
 6.76117785e-03 6.38196935e-03 6.03161964e-03 5.47959178e-03
 5.31982276e-03 4.94053065e-03 4.75719390e-03 4.44503201e-03
 4.18083430e-03 4.02014668e-03 3.86379602e-03 3.51494210e-03
 3.37999920e-03 3.27611341e-03 3.06389932e-03 2.96800834e-03
 2.73975192e-03 2.47130292e-03 2.34787212e-03 2.25426982e-03
 2.16884740e-03 1.97206849e-03 1.73637529e-03 1.68349894e-03
 1.57761084e-03 1.52650893e-03 1.37060284e-03 1.32614269e-03
 1.24928624e-03 1.19920249e-03 1.12824125e-03 1.09078106e-03
 1.02838717e-03 9.10916605e-04 7.63140297e-04 7.03312089e-04
 6.43801646e-04 6.26987850e-04 6.05599911e-04 5.46307475e-04
 5.33137602e-04 4.98413628e-04 4.79356626e-04 4.50425100e-04
 4.14833483e-04 4.09512743e-04 3.93211978e-04 3.68427489e-04
 3.55796683e-04 3.39546605e-04 3.08304937e-04 2.86444319e-04
 2.79415740e-04 2.65530016e-04 2.42645540e-04 2.38811208e-04
 2.11960780e-04 2.01717514e-04 1.98541623e-04 1.82372390e-04
 1.66663915e-04 1.61803179e-04 1.55808014e-04 1.39447282e-04
 1.23043321e-04 1.21398510e-04 1.11424513e-04 1.05721331e-04
 1.00708842e-04 9.94139729e-05 9.78167060e-05 9.17815574e-05]

 Total Variance Explained: 99.81

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,target
0,1.014826,1.151844,-0.590100,0.189230,0.050424,-0.309088,-0.161838,0.475817,0.972092,-0.044069,...,0.012398,0.021901,0.014938,0.009496,-0.000971,0.007413,-0.031283,-0.064994,-0.013006,2
1,-1.088554,0.290770,-1.767005,1.073354,-0.264096,-0.820615,-0.474019,-0.514266,0.709406,1.494247,...,-0.015573,-0.044234,0.042984,-0.002470,0.035771,-0.023970,-0.039238,-0.023468,0.006169,2
2,0.263657,-0.454794,0.107272,-0.422879,0.065537,0.692464,0.634806,-0.038230,0.804759,-0.919395,...,0.041988,-0.018405,-0.001843,0.062528,-0.099523,-0.053744,0.058064,-0.000709,0.056822,2
3,-1.520601,1.659013,-1.021584,0.803403,-0.285655,0.517912,0.355926,-0.342809,-0.918229,-0.619006,...,0.002631,-0.004883,0.025371,-0.067128,-0.011922,0.011281,0.028799,0.013097,-0.045798,2
4,-0.138578,-1.041365,0.350550,1.094308,-1.617382,1.483842,-0.113189,-0.251384,0.175558,-0.233899,...,-0.007791,-0.032268,0.044612,0.029736,-0.001336,-0.022603,-0.033480,0.002454,-0.033814,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,-1.324951,2.149106,0.788854,-1.306158,0.465976,-0.858739,-0.069472,-0.398438,0.741794,-0.582331,...,-0.033762,-0.072555,0.009339,-0.019832,0.006642,0.057092,0.029413,0.000688,0.006114,3
924,-0.865883,-0.042445,0.940661,0.303406,-0.472462,-0.368520,1.065665,0.804438,0.707684,0.935277,...,0.008971,0.063109,-0.050678,-0.027932,0.043407,-0.007981,-0.015099,-0.071286,-0.005980,3
925,3.737301,0.849177,-0.317751,-0.299680,0.598745,-0.254970,-0.057391,-0.076186,0.652850,-0.845358,...,-0.008677,-0.001486,-0.001174,-0.014430,0.024738,-0.066929,-0.002495,-0.035018,0.019395,3
926,0.596743,0.126431,0.003368,0.284843,0.167932,-0.156404,-0.068345,-0.184479,0.461735,-0.009070,...,0.059261,-0.013484,-0.025876,-0.062369,0.054519,0.023448,0.052085,0.013906,0.073373,3
927,-1.459645,1.228098,0.439525,0.281522,0.162962,-0.172032,-0.074895,0.034642,-0.000451,-0.693530,...,0.013628,0.088082,-0.012418,-0.021552,-0.026915,0.069126,-0.042632,-0.017067,-0.050208,3

#### **TRYING DIFFERENT ML MODELS ON A SINGLE LEAD(EX : 1) POST DIMENSIONALITY REDUCTION**

##### **KNN**

In [34]:
# Import the necessary modules for ML model
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Setup the pipeline steps:
steps = [('knn', KNeighborsClassifier())]

# Create the pipeline: pipeline
pipeline = Pipeline(steps)

# have paased less range value of hyperparamter since i'm using free tier version of google colab.
k_range = list(range(1, 9))
parameters = dict(knn__n_neighbors=k_range)

#input
X = result_df.iloc[:,0:-1]

#target
y=result_df.iloc[:,-1]

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=42)

#increasing cv score takes lot of time in gooogle colab, so kept it just 2.
cv = GridSearchCV(pipeline,parameters,cv=2)

cv.fit(X_train,y_train)

# Predict the labels of the test set: y_pred
y_pred = cv.predict(X_test)

Knn_Accuracy = cv.score(X_test, y_test)

# Compute and print metrics
print("Accuracy: {}".format(Knn_Accuracy))
print(classification_report(y_test, y_pred))
print("Tuned Model Parameters: {}".format(cv.best_params_))

Accuracy: 0.782258064516129
              precision    recall  f1-score   support

           0       0.87      0.63      0.73       105
           1       0.91      0.91      0.91        94
           2       0.72      0.88      0.79       112
           3       0.63      0.67      0.65        61

    accuracy                           0.78       372
   macro avg       0.78      0.77      0.77       372
weighted avg       0.80      0.78      0.78       372

Tuned Model Parameters: {'knn__n_neighbors': 1}

##### **LOGISTIC REGRESSION**

In [35]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Setup the pipeline steps:
steps = [('lr', LogisticRegression())]

# Create the pipeline: pipeline
pipeline = Pipeline(steps)

#input
X = result_df.iloc[:,0:-1]

#target
y=result_df.iloc[:,-1]

#parameters for gridsearchcv if we increase range of entries from 5 to higher value, we can get greater accurange
c_space = np.logspace(-4, 4, 3)
parameters = {'lr__C': c_space,'lr__penalty': ['l2']}

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=42)

#call GridSearchCV and set crossvalscore to 2
cv = GridSearchCV(pipeline,parameters,cv=2)

cv.fit(X_train,y_train)

# Predict the labels of the test set: y_pred
y_pred = cv.predict(X_test)
LR_Accuracy = cv.score(X_test, y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [36]:
# Compute and print metrics
print("Accuracy: {}".format(LR_Accuracy))
print(classification_report(y_test, y_pred))
print("Tuned Model Parameters: {}".format(cv.best_params_))

Accuracy: 0.5483870967741935
              precision    recall  f1-score   support

           0       0.38      0.34      0.36       105
           1       0.73      0.91      0.81        94
           2       0.56      0.58      0.57       112
           3       0.40      0.28      0.33        61

    accuracy                           0.55       372
   macro avg       0.52      0.53      0.52       372
weighted avg       0.52      0.55      0.53       372

Tuned Model Parameters: {'lr__C': 10000.0, 'lr__penalty': 'l2'}

##### **SVM**

In [37]:
# Import the necessary modules for ML model
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Setup the pipeline
steps = [('SVM', SVC())]

pipeline = Pipeline(steps)

#input
X = result_df.iloc[:,0:-1]

#target
y=result_df.iloc[:,-1]

# Specify the hyperparameter space, if we increase the penalty(c) and gamma value the accurancy can be increased.
#since it takes lots of time in google colab provided only a single value
parameters = {'SVM__C':[10],'SVM__gamma':[1]}

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=21)

cv = GridSearchCV(pipeline,parameters,cv=3)
cv.fit(X_train,y_train)

y_pred = cv.predict(X_test)
SVM_Accuracy = cv.score(X_test, y_test)

# Compute and print metrics
SVM_Accuracy=cv.score(X_test, y_test)

print("Accuracy: {}".format(SVM_Accuracy))
print(classification_report(y_test, y_pred))

Accuracy: 0.8225806451612904
              precision    recall  f1-score   support

           0       0.58      1.00      0.74        93
           1       1.00      1.00      1.00        99
           2       1.00      0.61      0.76       117
           3       1.00      0.68      0.81        63

    accuracy                           0.82       372
   macro avg       0.90      0.82      0.83       372
weighted avg       0.90      0.82      0.83       372

#### **NOW COMBINING ALL 12 LEADS INTO A SINGLE CSV FILE AND THEN PERFROM MODEL ANALYSIS**

In [40]:
#lets try combining all 12 leads in a single csv
location= '/content/drive/MyDrive/CSV_files_folder'

for files in natsorted(os.listdir(location)):
  if files.endswith(".csv") and not files.endswith("13.csv"):
    if files!='Combined_IDLead_1.csv':
      df=pd.read_csv('/content/drive/MyDrive/CSV_files_folder/{}'.format(files))
      df.drop(columns=['0'],inplace=True)
      test_final=pd.concat([test_final,df],axis=1,ignore_index=True)
      test_final.drop(columns=test_final.columns[-1],axis=1,inplace=True)

#drop the target column
test_final.drop(columns=[255],axis=1,inplace=True)
test_final

,0,1,2,3,4,5,6,7,8,9,...,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270
0,0.680755,0.619010,0.645367,0.681570,0.732488,0.758448,0.750660,0.728282,0.707928,0.710137,...,0.564020,0.591298,0.612891,0.597247,0.536243,0.476746,0.463167,0.504937,0.580023,0.652901
1,0.950695,0.941024,0.930501,0.913601,0.892244,0.868016,0.855127,0.835307,0.798640,0.733188,...,0.689768,0.742062,0.763032,0.789322,0.808960,0.831410,0.849130,0.861697,0.872784,0.890199
2,0.661575,0.695790,0.741113,0.716666,0.595794,0.425022,0.286457,0.425022,0.611384,0.775065,...,0.406550,0.290411,0.172322,0.079423,0.105674,0.222326,0.337158,0.405090,0.418269,0.390249
3,0.861690,0.866457,0.865756,0.855027,0.855606,0.845561,0.843187,0.846784,0.824438,0.788354,...,0.695700,0.733912,0.771743,0.778749,0.783443,0.789026,0.794001,0.800782,0.776099,0.736342
4,0.924369,0.873765,0.791381,0.699513,0.604927,0.500312,0.446012,0.528910,0.634068,0.732402,...,0.095457,0.166030,0.272365,0.376568,0.489110,0.592626,0.701895,0.801839,0.884201,0.912979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,0.877014,0.864280,0.860505,0.871349,0.912404,0.958148,0.977826,0.956314,0.926773,0.906898,...,0.893079,0.896180,0.822645,0.754790,0.761535,0.811766,0.830802,0.822607,0.785315,0.758195
924,0.832084,0.852396,0.909665,0.988242,1.000000,0.923323,0.821865,0.721302,0.612039,0.544501,...,0.297933,0.394040,0.483825,0.574441,0.673272,0.743376,0.808244,0.863312,0.887649,0.895122
925,0.417983,0.362322,0.351995,0.391493,0.418305,0.440135,0.444598,0.460402,0.506810,0.582590,...,0.804402,0.805049,0.792891,0.766632,0.734628,0.698830,0.644917,0.597843,0.592362,0.635767
926,0.682286,0.641051,0.620212,0.608210,0.576331,0.603596,0.645714,0.677964,0.720297,0.727853,...,0.698232,0.662505,0.618233,0.571661,0.538323,0.548877,0.605038,0.662948,0.704631,0.742343
927,0.815695,0.819518,0.820559,0.847985,0.880933,0.902061,0.878266,0.838806,0.811795,0.790403,...,0.428456,0.401992,0.423779,0.421313,0.413477,0.393341,0.396764,0.413491,0.398432,0.409180

In [41]:
#write the file to csv
test_final.to_csv('final_1D.csv',header=False,index=False)

#### **TEST DIMENSIONALITY REDUCTION EXPLAINED VARIANCE ON  THE DATA**
**NOTE: CURRENTLY NOT USED IN THE FINAL TEST MODEL **

In [42]:
# Now Perform Dimensionality reduction (PCA) on that Dataframe and check
from sklearn.decomposition import PCA

#do PCA and choose componeents as 400
pca = PCA(n_components=400)
x_pca = pca.fit_transform(test_final)
x_pca = pd.DataFrame(x_pca)

# Calculate the variance explained by priciple components
explained_variance = pca.explained_variance_ratio_
print('Variance of each component:', pca.explained_variance_ratio_)
print('\n Total Variance Explained:', round(sum(list(pca.explained_variance_ratio_))*100, 2))

#store the new pca generated dimensions in a dataframe
#store the new pca generated dimensions in a dataframe
pca_df = pd.DataFrame(data = x_pca)
target = pd.Series(result_df.iloc[:,-1], name='target')
final_result_df = pd.concat([pca_df, target], axis=1)
final_result_df

Variance of each component: [9.64578397e-02 4.57441956e-02 4.04839082e-02 3.50927000e-02
 2.97036351e-02 2.81088683e-02 2.55889872e-02 2.43908756e-02
 2.37594835e-02 2.21795728e-02 2.03112982e-02 1.91738279e-02
 1.78865138e-02 1.77424151e-02 1.64975374e-02 1.59783928e-02
 1.53265476e-02 1.44315425e-02 1.39723693e-02 1.31469362e-02
 1.26452802e-02 1.23048250e-02 1.17332657e-02 1.11513175e-02
 1.10416129e-02 1.05673035e-02 9.89838553e-03 9.75080089e-03
 9.46711047e-03 9.20456494e-03 9.08511618e-03 8.67345156e-03
 8.48935413e-03 8.16613776e-03 8.05561427e-03 7.70957384e-03
 7.39208208e-03 6.99755041e-03 6.87006906e-03 6.58695600e-03
 6.34883970e-03 6.26763626e-03 6.13649220e-03 5.86939012e-03
 5.58179281e-03 5.57464732e-03 5.45859027e-03 5.29309926e-03
 5.07463061e-03 4.89617782e-03 4.83809798e-03 4.65845846e-03
 4.44516436e-03 4.42840657e-03 4.24533252e-03 4.13466149e-03
 4.04612318e-03 4.00621038e-03 3.88806359e-03 3.80057410e-03
 3.72168101e-03 3.63039878e-03 3.56445007e-03 3.47509358e-03
 3.45434297e-03 3.34507076e-03 3.21021361e-03 3.14620587e-03
 3.10679595e-03 2.98494028e-03 2.93616627e-03 2.90789051e-03
 2.79368010e-03 2.73412544e-03 2.67058931e-03 2.65242699e-03
 2.64354428e-03 2.51948472e-03 2.46683968e-03 2.41664429e-03
 2.40602697e-03 2.30131982e-03 2.27190758e-03 2.25115476e-03
 2.19977283e-03 2.17274354e-03 2.16611260e-03 2.10310023e-03
 1.99848426e-03 1.95358837e-03 1.93371218e-03 1.85854252e-03
 1.83202993e-03 1.79038547e-03 1.75986341e-03 1.74152703e-03
 1.72841600e-03 1.68031689e-03 1.62874451e-03 1.60807679e-03
 1.55122035e-03 1.51293119e-03 1.49770202e-03 1.48114459e-03
 1.44809638e-03 1.42053493e-03 1.38628908e-03 1.33252486e-03
 1.32620914e-03 1.30601891e-03 1.29050856e-03 1.27442776e-03
 1.25774094e-03 1.23450172e-03 1.20988044e-03 1.17859875e-03
 1.16091789e-03 1.14675749e-03 1.10961882e-03 1.10440838e-03
 1.06254553e-03 1.04464056e-03 1.03206286e-03 1.01793747e-03
 9.89008789e-04 9.60403110e-04 9.31486541e-04 8.90059061e-04
 8.85441644e-04 8.74094613e-04 8.61762109e-04 8.52089229e-04
 8.35557752e-04 7.95466247e-04 7.89104477e-04 7.75389579e-04
 7.70700798e-04 7.52788345e-04 7.16748820e-04 7.15223892e-04
 6.99974773e-04 6.86221437e-04 6.70367498e-04 6.67877034e-04
 6.54721806e-04 6.35620200e-04 6.30086519e-04 6.16857384e-04
 6.06102467e-04 5.95040056e-04 5.78777677e-04 5.68587385e-04
 5.57489701e-04 5.52708942e-04 5.45164772e-04 5.25967302e-04
 5.20719269e-04 5.06525944e-04 4.94850285e-04 4.89167097e-04
 4.72745694e-04 4.71236869e-04 4.62124803e-04 4.44197546e-04
 4.38270764e-04 4.34207631e-04 4.28518568e-04 4.00024401e-04
 3.91811601e-04 3.89793314e-04 3.87240640e-04 3.83849747e-04
 3.73274329e-04 3.64407004e-04 3.61351569e-04 3.48965004e-04
 3.38642010e-04 3.32253505e-04 3.31671717e-04 3.21034371e-04
 3.16298549e-04 3.11575548e-04 3.03012475e-04 2.92529702e-04
 2.91281971e-04 2.87729808e-04 2.75636520e-04 2.74662534e-04
 2.70203063e-04 2.62486209e-04 2.55022477e-04 2.52719982e-04
 2.43888957e-04 2.42932404e-04 2.40308066e-04 2.34968489e-04
 2.25721859e-04 2.22167233e-04 2.17443497e-04 2.17208763e-04
 2.11604041e-04 2.08439606e-04 1.98968223e-04 1.98045546e-04
 1.92384470e-04 1.91370582e-04 1.85223828e-04 1.84208188e-04
 1.80592990e-04 1.78317945e-04 1.72449175e-04 1.67666601e-04
 1.62018560e-04 1.59543701e-04 1.52173810e-04 1.50956285e-04
 1.49065672e-04 1.47991486e-04 1.43815202e-04 1.40463059e-04
 1.37309472e-04 1.33411202e-04 1.31077728e-04 1.29492208e-04
 1.26550070e-04 1.24518544e-04 1.22158023e-04 1.16200483e-04
 1.14625462e-04 1.12461965e-04 1.10033225e-04 1.07863022e-04
 1.06755809e-04 1.04799274e-04 1.00793529e-04 9.92134001e-05
 9.79652914e-05 9.68600293e-05 9.41073232e-05 9.26217242e-05
 9.06759613e-05 9.01209136e-05 8.79551170e-05 8.62111033e-05
 8.44929928e-05 8.23768512e-05 8.19227675e-05 8.12559642e-05
 7.73053301e-05 7.58882443e-05 7.53280284e-05 7.37241682e-05
 7.28043428e-05 7.25859986e-05 7.01614428e-05 6.91035557e-05
 6.73860282e-05 6.64849380e-05 6.48888134e-05 6.43430513e-05
 6.27218704e-05 6.22881220e-05 5.99361527e-05 5.86207339e-05
 5.83932845e-05 5.64826791e-05 5.55600519e-05 5.46868113e-05
 5.31544956e-05 5.20576667e-05 5.09156733e-05 4.99253787e-05
 4.91306421e-05 4.84436332e-05 4.82562226e-05 4.80955933e-05
 4.59287455e-05 4.50678433e-05 4.39041697e-05 4.36951151e-05
 4.31714570e-05 4.23867919e-05 4.15646145e-05 4.13147961e-05
 4.10332504e-05 4.00032712e-05 3.96646705e-05 3.82574943e-05
 3.75587319e-05 3.68507200e-05 3.61962735e-05 3.56335808e-05
 3.49602291e-05 3.42727765e-05 3.40590720e-05 3.34825521e-05
 3.27849932e-05 3.25092200e-05 3.14925562e-05 3.12996794e-05
 3.08302132e-05 2.98142701e-05 2.95919764e-05 2.91848711e-05
 2.82697199e-05 2.82005330e-05 2.77558629e-05 2.72648498e-05
 2.67285069e-05 2.62971577e-05 2.56929606e-05 2.53741462e-05
 2.50813790e-05 2.41321770e-05 2.38555235e-05 2.37428337e-05
 2.35867681e-05 2.31896981e-05 2.30002482e-05 2.24316605e-05
 2.19949065e-05 2.19504662e-05 2.15316954e-05 2.11674124e-05
 2.01684844e-05 1.99796540e-05 1.96786260e-05 1.95516609e-05
 1.91463228e-05 1.88755367e-05 1.83812452e-05 1.79565830e-05
 1.76847757e-05 1.73874214e-05 1.70845883e-05 1.69639787e-05
 1.63358069e-05 1.63041878e-05 1.61396037e-05 1.58215699e-05
 1.55257590e-05 1.52330627e-05 1.48850321e-05 1.46233807e-05
 1.43720942e-05 1.43355982e-05 1.40668954e-05 1.35381714e-05
 1.33214604e-05 1.30919983e-05 1.28291588e-05 1.25278983e-05
 1.23856511e-05 1.22376307e-05 1.21438417e-05 1.18778433e-05
 1.16383936e-05 1.14412991e-05 1.13458357e-05 1.11932474e-05
 1.11135537e-05 1.07119641e-05 1.05223914e-05 1.03195285e-05
 1.01060491e-05 1.00696552e-05 9.90875942e-06 9.81513316e-06
 9.68118639e-06 9.53456854e-06 9.45963731e-06 9.24587992e-06
 9.18568566e-06 8.84285012e-06 8.63666188e-06 8.41100745e-06
 8.21398873e-06 7.96406742e-06 7.82293134e-06 7.74444476e-06
 7.61260293e-06 7.59041227e-06 7.43205881e-06 7.23478926e-06
 7.11028825e-06 7.01112472e-06 6.87564518e-06 6.85054103e-06
 6.73676299e-06 6.63450509e-06 6.47958205e-06 6.35763352e-06
 6.15320542e-06 6.01273221e-06 5.92139793e-06 5.81680059e-06
 5.78271158e-06 5.71324864e-06 5.55072049e-06 5.36538998e-06]

 Total Variance Explained: 99.98

,0,1,2,3,4,5,6,7,8,9,...,391,392,393,394,395,396,397,398,399,target
0,1.797118,-2.416601,-1.937024,-0.470651,-0.124461,-0.937029,-0.142501,-0.344762,-0.972874,-0.911867,...,-0.032861,-0.040649,0.030883,-0.014895,-0.015944,-0.008160,-0.027331,-0.012369,0.027267,2
1,-2.194939,2.408098,-0.245811,-1.560190,1.294371,-1.326001,-0.339551,0.183651,0.521519,1.430174,...,-0.006275,0.007973,-0.030079,0.028906,0.019188,0.007709,0.009574,0.011502,0.014733,2
2,2.705968,0.900354,2.364326,2.083788,0.078796,-0.077855,1.532532,0.364096,0.793730,0.852247,...,0.008770,0.024004,0.023945,0.018981,-0.022212,0.017060,-0.005995,-0.004830,0.000482,2
3,-2.097050,-2.728984,-2.237204,-0.154353,3.546408,-1.201380,0.919685,-0.762929,0.332577,0.611865,...,0.003932,0.007744,0.023139,0.009800,0.011534,-0.054225,0.006786,0.013253,0.036742,2
4,-3.514908,-0.809742,0.400796,1.252031,0.699474,1.860329,-2.408273,-0.779888,-2.848908,-0.356475,...,-0.040630,0.006871,0.005411,0.017750,-0.001018,0.025560,0.019295,0.001437,-0.017522,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,-2.581179,-1.251390,-0.018928,-2.281078,1.176323,1.971604,1.931536,-1.792066,1.171144,0.886461,...,-0.002878,0.042785,0.015953,0.002577,0.013025,0.002140,0.019301,0.018329,0.004205,3
924,-3.240658,-3.010528,1.110535,-1.060033,0.274984,0.697060,4.276440,-0.787304,-1.285655,-1.370176,...,0.016954,0.006206,0.013321,-0.004511,-0.019055,-0.016351,-0.015518,-0.010255,-0.032108,3
925,-1.006224,2.812228,0.593407,-1.509733,-0.037106,0.654664,0.218756,-1.094487,-1.738217,0.322471,...,-0.004677,0.004470,-0.026570,0.022012,0.012919,-0.003904,0.031444,-0.018554,0.015777,3
926,2.026390,1.552147,-1.038667,-0.366104,1.550039,-1.019249,-2.116111,-0.227262,-0.181219,-3.117454,...,-0.022376,0.040186,-0.010309,-0.011558,0.008606,0.003152,0.022693,0.029938,-0.024256,3
927,2.026070,4.047574,-1.613578,-1.203147,0.101535,-1.190579,0.645457,-0.354370,0.223942,1.980071,...,0.036186,0.000301,-0.006758,0.001353,0.034225,-0.010148,-0.007071,0.008995,-0.002197,3

#### **TRYING DIFFERENT ML MODELS ON THE ALL 12 LEADS COMBINED FILE WITHOUT DIMENSIONALITY REDUCTION**

##### **KNN**

In [43]:
# Import the necessary modules for ML model
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Setup the pipeline steps:
steps = [('knn', KNeighborsClassifier())]

# Create the pipeline: pipeline
pipeline = Pipeline(steps)

# have paased less range value of hyperparamter since i'm using free tier version of google colab.
k_range = list(range(1, 30))
parameters = dict(knn__n_neighbors=k_range)

#input
X = pd.read_csv('final_1D.csv',header=None)

#target
y=final_result_df.iloc[:,-1]

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=42)

#increasing cv score takes lot of time in gooogle colab, so kept it just 2.
cv = GridSearchCV(pipeline,parameters,cv=2)

cv.fit(X_train,y_train)

# Predict the labels of the test set: y_pred
y_pred = cv.predict(X_test)

Knn_Accuracy = cv.score(X_test, y_test)

# Compute and print metrics
print("Accuracy: {}".format(Knn_Accuracy))
print(classification_report(y_test, y_pred))
print("Tuned Model Parameters: {}".format(cv.best_params_))

Accuracy: 0.7903225806451613
              precision    recall  f1-score   support

           0       0.95      0.71      0.82       105
           1       0.89      0.91      0.90        94
           2       0.71      0.82      0.76       112
           3       0.62      0.67      0.65        61

    accuracy                           0.79       372
   macro avg       0.79      0.78      0.78       372
weighted avg       0.81      0.79      0.79       372

Tuned Model Parameters: {'knn__n_neighbors': 1}

##### **LOGISTIC REGRESSION**

In [44]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Setup the pipeline steps:
steps = [('lr', LogisticRegression())]

# Create the pipeline: pipeline
pipeline = Pipeline(steps)

#input
X = pd.read_csv('final_1D.csv',header=None)

#target
y=final_result_df.iloc[:,-1]

#parameters for gridsearchcv
c_space = np.logspace(-4, 4, 10)
parameters = {'lr__C': c_space,'lr__penalty': ['l2']}

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=42)

#call GridSearchCV and set crossvalscore to 2
cv = GridSearchCV(pipeline,parameters,cv=2)

cv.fit(X_train,y_train)

# Predict the labels of the test set: y_pred
y_pred = cv.predict(X_test)
LR_Accuracy = cv.score(X_test, y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [45]:
# Compute and print metrics
print("Accuracy: {}".format(LR_Accuracy))
print(classification_report(y_test, y_pred))
print("Tuned Model Parameters: {}".format(cv.best_params_))

Accuracy: 0.9193548387096774
              precision    recall  f1-score   support

           0       0.93      0.94      0.93       105
           1       0.88      0.91      0.90        94
           2       0.93      0.93      0.93       112
           3       0.96      0.87      0.91        61

    accuracy                           0.92       372
   macro avg       0.92      0.91      0.92       372
weighted avg       0.92      0.92      0.92       372

Tuned Model Parameters: {'lr__C': 21.54434690031882, 'lr__penalty': 'l2'}

##### **SVM**

In [46]:
# Import the necessary modules for ML model
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report

# Setup the pipeline
steps = [('SVM', SVC())]

pipeline = Pipeline(steps)

#input
X = pd.read_csv('final_1D.csv',header=None)

#target
y=final_result_df.iloc[:,-1]

# Specify the hyperparameter space, if we increase the penalty(c) and gamma value the accurancy can be increased.
#since it takes lots of time in google colab provided only a single value
parameters = {'SVM__C':[1, 10, 100],
              'SVM__gamma':[0.1, 0.01]}

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.5,random_state=21)

cv = GridSearchCV(pipeline,parameters,cv=3)
cv.fit(X_train,y_train)

y_pred = cv.predict(X_test)
SVM_Accuracy = cv.score(X_test, y_test)

# Compute and print metrics
SVM_Accuracy=cv.score(X_test, y_test)

print("Accuracy: {}".format(SVM_Accuracy))
print(classification_report(y_test, y_pred))

Accuracy: 0.9806034482758621
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       119
           1       1.00      1.00      1.00       125
           2       0.94      1.00      0.97       140
           3       1.00      0.90      0.95        80

    accuracy                           0.98       464
   macro avg       0.98      0.97      0.98       464
weighted avg       0.98      0.98      0.98       464

#### **SAVING A VERY BASIC ML MODEL AND USING IT ON REALTIME PIPELINE TO CHECK WORKING**

In [47]:
# Import the necessary modules for ML model
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report
import joblib
#input
X = pd.read_csv('final_1D.csv',header=None)

#target
y=final_result_df.iloc[:,-1]

# Create train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=42)

knn =  KNeighborsClassifier(n_neighbors=1)

knn.fit(X_train,y_train)

joblib_file='model_test.pkl'
joblib.dump(knn,joblib_file)

['model_test.pkl']

## SAVE AND USE THE ABOVE MODEL IN THE STREAMLIT APP : **https://colab.research.google.com/drive/139YVmcUBCiP52J2sX3QE_eiu2sukVgpn?usp=sharing**